apiVersion: v1
kind: Service
metadata:
  name: aqua-db
  labels:
    app: aqua-db
spec:
  ports:
  - port: 5432
  externalName: <Managed_DB_DNS_Name>
  selector:
    app: aqua-db
  type: ExternalName

