apiVersion: v1
kind: ConfigMap
metadata:
  name: aqua-csp-db-config
  namespace: aqua
data:
  AQUA_ENV_SIZE: "S" # Possible values: “S”, “M”, “L”, defaults to “S”.
  PGDATA: "/var/lib/postgresql/data/db-files"