apiVersion: v1
data:
  ### Aqua database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Aqua database password secret
  labels:
    deployedby: aqua-yaml
  name: aqua-db
  namespace: aqua
type: Opaque
---
apiVersion: v1
data:
  ### Aqua database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Aqua audit database password secret
  labels:
    deployedby: aqua-yaml
  name: aqua-audit-db
  namespace: aqua
type: Opaque