apiVersion: v1
kind: Service
metadata:
  name: aqua-tenantmanager
  namespace: aqua
  labels:
    app: aqua-tenantmanager
spec:
  ports:
    - port: 8081
      name: aqua-tenantmanager
      protocol: TCP
      targetPort: 8081
    - port: 443
      name: aqua-tenantmanager-ssl
      protocol: TCP
      targetPort: 8444
  selector:
    app: aqua-tenantmanager
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-tenantmanager
  namespace: aqua
spec:
  selector:
    matchLabels:
      app: aqua-tenantmanager
  template:
    metadata:
      labels:
        app: aqua-tenantmanager
      name: aqua-tenantmanager
    spec:
      serviceAccount: aqua-sa
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      containers:
        - name: aqua-tenantmanager
          image: registry.aquasec.com/tenantmanager:5.3
          env:
            - name: AQUA_TM_DBNAME
              value: "tenantmanager"
            - name: AQUA_TM_DBUSER
              value: "postgres"
            - name: AQUA_TM_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: aqua-tm-db
                  key: password
            - name: AQUA_TM_DBHOST
              value: aqua-tm-db
            - name: AQUA_TM_DBPORT
              value: "5432"
            - name: AQUA_TM_AUDIT_DBNAME
              value: "tm_audit"
            - name: AQUA_TM_AUDIT_DBUSER
              value: "postgres"
            - name: AQUA_TM_AUDIT_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: aqua-tm-db
                  key: password
            - name: AQUA_TM_AUDIT_DBHOST
              value: aqua-tm-db
            - name: AQUA_TM_AUDIT_DBPORT
              value: "5432"
            - name: SCALOCK_LOG_LEVEL
              value: "DEBUG"
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8444
              protocol: TCP
