apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: aqua-tm-db-pvc
  namespace: aqua
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
