apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kube-enforcer-admission-hook-config
  namespace: aqua
webhooks:
  - name: imageassurance.aquasec.com
    failurePolicy: Ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods", "deployments", "replicasets", "replicationcontrollers", "statefulsets", "daemonsets", "jobs", "cronjobs"]
    clientConfig:
      # Configure the CA certificate in the below caBundle
      # caBundle: <ca_bundle>
      service:
        namespace: aqua
        name: aqua-kube-enforcer
    timeoutSeconds: 5
    admissionReviewVersions: ["v1beta1"]	
    sideEffects: "None"