apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Aqua Scanner username and password
  labels:
    deployedby: aqua-yaml
  name: aqua-scanner
  namespace: aqua
type: Opaque
data:
  # Aqua Scanner Username - Base64 Encoded
  AQUA_SCANNER_USERNAME: ""
  # Aqua Scanner Password - Base64 Encoded
  AQUA_SCANNER_PASSWORD: ""
  # Base64 Encoded - Aqua Server IP/Domain/Servicename followed by HTTPS port.
  AQUA_SERVER: ""
    # Base64 Encoded - Aqua web root cert
  aqua-web-root-cert: ""
  
